#!/bin/bash

# 1. Run the pipeline
# We usage the 'unbuffer' command (optional) or just plain python to ensure logs appear in real-time.
# chmod +x run_pipeline.sh
python pipeline.py

# 2. Capture the exit code of the Python script
EXIT_CODE=$?

# 3. Check if Python crashed (Exit code non-zero)
if [ $EXIT_CODE -ne 0 ]; then
    echo "--------------------------------------------------"
    echo "❌ FAILURE: The Python script crashed (Exit Code: $EXIT_CODE)."
    echo "Check 'logs/execution.log' or 'terminal_output.txt' for the traceback."
    exit $EXIT_CODE
fi

# 4. Check the logs for specific application errors
# We grep the log file generated by Python
if grep -q "CRITICAL ERROR" terminal_output.txt; then
    echo "--------------------------------------------------"
    echo "⚠️  WARNING: Script finished, but critical errors were detected."
    echo "Check 'terminal_output.txt' for details."
    exit 1
fi

echo "--------------------------------------------------"
echo "✅ SUCCESS: JailbreakBench pipeline completed."